name: Build & Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    name: Build module ZIP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install composer dependencies
        run: composer install --no-dev -o

      - name: Create installable module ZIP
        run: |
          cd ${{ github.workspace }}/..
          zip -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }} \
            --exclude "*/.git/*" \
            --exclude "*/.git" \
            --exclude "*/.ddev/*" \
            --exclude "*/tests/*" \
            --exclude "*/node_modules/*" \
            --exclude "*/.github/*" \
            --exclude "*/Makefile" \
            --exclude "*/.php-cs-fixer*" \
            --exclude "*/.editorconfig" \
            --exclude "*/docker-compose.yml"
          mv ${{ github.event.repository.name }}.zip ${{ github.workspace }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.event.repository.name }}.zip

  release:
    name: Attach ZIP to GitHub Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
